---
- type: replace
  path: /instance_groups/-
  value:
    name: tests
    azs: [ z1 ]
    instances: 1
    lifecycle: errand
    post_deploy: true
    jobs:
      - name: smoke-tests
        release: minio
        templates:
          - name: smoke-tests
        consumes:
          minio: { from: minio-link }
