---
- type: replace
  path: /instance_groups/-
  value:
    name: tests
    azs: [ z1 ]
    instances: 1
    lifecycle: errand
    post_deploy: true
    networks: [ { name: default } ]
    vm_type: default
    stemcell: default
    jobs:
      - name: smoke-tests
        release: minio
        properties:
          bucket_test:
            create_bucket: true
            delete_bucket: true
          object_test:
            object_size_kb: 1024
            number_of_threads: 4
            number_of_uploads_in_thread: 100
            check_uploaded_objects: true
            delete_uploaded_objects: true
