minio_instances: 3
minio_storage_class_standard: "EC:1"
minio_vm_type: default
minio_disk_type: 10GB

minio_root_user: "root"
minio_root_password: "If-you-really-love-security-then-you-will-change-me!"

minio_console_uri: minio-console-rnd.example.org
minio_api_uri: minio-api-rnd.example.org

credhub_base_url: https://credhub-dev.example.org:8844
credhub_client:
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----
credhub_server_ca:
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
